language: python
dist: trusty
sudo: required

services:
- docker

branches:
  except:
    - /^v\d+\.*$/
    - gh-pages
    - travis-*
    - /^untagged.*/
    - /^feature.*/
matrix:
  include:
  - python: "3.5"
    env:
    - FLAG=false
      TOXENV=py35
  - python: "3.6"
    env:
    - FLAG=true
      TOXENV=py36
      MODEL_FILE=Cartpole-$TRAVIS_BUILD_NUMBER.h5
install:
- travis_retry pip install tox

script:
- make clean test
- if [[ $FLAG == 'true' ]]; then
     make EPOCHS_TRAIN="$EPOCHS_TRAIN" MODEL_FILE="$MODEL_FILE" train;
  fi

deploy:
- provider: gcs
  skip_cleanup: true
  access_key_id: $GCS_ACCESS_KEY_ID
  secret_access_key: $GCS_SECRET_ACCESS_KEY
  bucket: "cartpole"
  local-dir: seldon/models
  on:
    branch: master
    condition: $FLAG = true

- provider: script
  skip_cleanup: true
  script: >-
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    make MODEL_FILE="$MODEL_FILE" seldon-build seldon-push
  on:
    branch: master
    condition: $FLAG = true

- provider: script
  skip_cleanup: true
  script: ./cicd.sh
  on:
    branch: master
    condition: $FLAG = true
