language: python
dist: trusty
sudo: false
branches:
  except:
    - /^v\d+\.*$/
    - gh-pages
    - travis-*
    - /^untagged.*/
    - /^feature.*/
matrix:
  include:
  - python: "3.5"
    env:
    - FLAG=false
      TOXENV=py35
  - python: "3.6"
    env:
    - FLAG=true
      TOXENV=py36
      MODEL_FILE=Cartpole-${TRAVIS_BUILD_NUMBER}.h5
      EPOCHS_TRAIN=500
install:
- travis_retry pip install tox

script:
- make clean test
- if [[ $FLAG == 'true' ]]; then
     make train;
  fi

deploy:
- provider: gcs
  skip_cleanup: true
  access_key_id: $GCS_ACCESS_KEY_ID
  secret_access_key: $GCS_SECRET_ACCESS_KEY
  bucket: "cartpole"
  local-dir: build/model
  on:
    branch: master
    condition: $FLAG = true

- provider: script
  skip_cleanup: true
  script: >-
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    make seldon-build seldon-push
  on:
    branch: master
    condition: $FLAG = true
