version: '3.3'

services:
  visdom:
    environment:
    - HOSTNAME=visdom
    image: hypnosapos/visdom:latest
    networks:
      default:
        aliases:
        - visdom
    ports:
    - "8097:8097"
  cartpole-rl-remote:
    depends_on:
    - visdom
    image: hypnosapos/cartpole-rl-remote:${DOCKER_TAG:-latest}
    command: >-
      cartpole --log-level DEBUG -e 400
      --metrics-engine visdom --metrics-config '{"server": "http://35.195.122.47", "env": "main"}'
      train --gamma 0.095 0.099 0.001 --batch_size 32 33 -f /tmp/seldon/models/cartpole-rl-remote
    volumes:
    - ./seldon/models:/tmp/seldon/models
