version: '3.3'

services:
  visdom:
    environment:
    - HOSTNAME=visdom
    image: hypnosapos/visdom:latest
    networks:
      default:
        aliases:
        - visdom
    ports:
    - "8097:8097"
  train-cartpole:
    depends_on:
    - visdom
    build: ./
    image: hypnosapos/${DOCKER_IMAGE:-cartpole-rl-remote}:${DOCKER_TAG:-latest}
    command: >-
      cartpole --log-level DEBUG -e 200
      --metrics-engine visdom --metrics-config '{"server": "http://visdom", "env": "main"}'
      train --gamma 0.095 0.099 0.001 --batch_size 32 33 -f /tmp/seldon/models/cartpole-rl-remote
    volumes:
    - ./seldon/models:/tmp/seldon/models
