version: '2'
services:
  cartpole:
    depends_on:
      - elasticsearch
      - kibana
    build: ./
    image: hypnosapos/cartpole-rl-remote:latest
    command: >-
      cartpole --log-level DEBUG -e 200
      train --gamma 0.095 0.099 0.001 -f /tmp/seldon/models/cartpole-rl-remote
    volumes:
    - ./seldon/models:/tmp/seldon/models
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: cartpole

  fluentd:
    depends_on:
    - elasticsearch
    build: ./fluentd
    volumes:
      - ./efk//fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "5140:5140"

  elasticsearch:
    image: elasticsearch
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    depends_on:
    - elasticsearch
    image: kibana
    # image: docker.elastic.co/kibana/kibana:6.3.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"