version: 2
jobs:
  "3.5":
    machine: true

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install -U ipdb tox tox-pyenv
            pyenv local '3.5.2'
      - run:
          name: test
          command: |
            tox -e py35
      - run:
          name: install
          command: |
            make install
      - run:
          name: train
          command: |
            make EPOCHS_TRAIN=$EPOCHS_TRAIN MODEL_FILE=$MODEL_FILE train
          environment:
            MODEL_FILE: Cartpole-rl-remote-$CIRCLE_BUILD_NUM.h5
            EPOCHS_TRAIN: 2000
  "3.6":
    docker:
    - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install tox
      - run:
          name: test
          command: |
            tox -e py36
      - run:
          name: install
          command: |
            make install
  "gce":
    docker:
    - image: google/cloud-sdk
    steps:
    - run: gcloud version

workflows:
  version: 2
  build:
    jobs:
      - "3.5"
      - "3.6"
      - "gce"
        requires:
        - "3.5"