version: 2
jobs:
  "3.5":
    machine: true
    working_directory: ~/repo
    environment:
      EPOCHS_TRAIN: 1000
    steps:
      - checkout
      - run:
          command: |
            pyenv local 3.5.2
            pip install -U pip ipdb tox tox-pyenv
            tox -e py35
            make install
            make EPOCHS_TRAIN=${EPOCHS_TRAIN} MODEL_FILE=Cartpole-rl-remote-${CIRCLE_BUILD_NUM}.h5 train
  "3.6":
    docker:
    - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install tox
      - run:
          name: test
          command: |
            tox -e py36
      - run:
          name: install
          command: |
            make install
  gce:
    docker:
    - image: google/cloud-sdk
    steps:
    - run: gcloud version

workflows:
  version: 2
  build:
    jobs:
    - "3.6"
    - "3.5":
        requires:
        - "3.6"
    - gce:
        requires:
        - "3.5"