version: 2
jobs:
  "3.5":
    docker:
    - image: python:3.5
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: install requirements
          command: |
            pip install tox
      - run:
          name: test
          command: |
            tox -e py35
      - run:
          name: install and train
          command: |
            make EPOCHS_TRAIN=${EPOCHS_TRAIN} install train
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: build and push seldon image
          command: |
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            make seldon-clean seldon-build seldon-push
  "3.6":
    docker:
    - image: python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install tox
    - run:
        name: test
        command: |
          tox -e py36
    - run:
        name: install
        command: |
          make install
  gce:
    docker:
    - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
    - checkout
    - run:
       name: configure gcloud client
       command: |
         echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
         gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
         gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
         gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
         gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
    - run:
        name: Deploy SeldonDeployment
        command: |
          kubectl apply -f seldon/cartpole_seldon.json

workflows:
  version: 2
  build:
    jobs:
    - "3.6"
    - "3.5":
        requires:
        - "3.6"
    - gce:
        requires:
        - "3.5"