version: 2
jobs:
  "3.5":
    docker:
    - image: python:3.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install tox
      - run:
          name: test
          command: |
            tox -e py35
      - run:
          name: install
          command: |
            make install
  "3.6":
    docker:
    - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install tox
      - run:
          name: test
          command: |
            tox -e py36
      - run:
          name: install
          command: |
            make install
      - run:
          name: train
          command: |
            make train
          environment:
            MODEL_FILE: Cartpole-rl-remote-$CIRCLE_BUILD_NUM.h5
workflows:
  version: 2
  build:
    jobs:
      - "3.5"
      - "3.6"