version: 2

jobs:

  tests:
    docker:
    - image: docker
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
        name: Install essentials
        command: |
          apk add --no-cache --virtual .build-deps make gcc
    - run:
        name: launch tests
        command: |
          make test

  gke_cluster:
    docker:
    - image: docker
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
       name: GCP key file
       command: |
         echo ${GOOGLE_AUTH} > ${HOME}/gcp.json
    - run:
       name: GKE cluster
       command: |
         make gke-bastion gke-create-cluster gke-tiller-helm

  polyaxon:
    docker:
    - image: docker
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
       name: Polyaxon installation
       command: |
         make -C polyaxon gke-polyaxon-preinstall gke-polyaxon-install
    - run:
       name: Polyaxon init for cartpole project
       command: |
         make -C polyaxon gke-polyaxon-cartpole-init
    - run:
       name: Cartpole training
       command: |
         make -C polyaxon gke-polyaxon-cartpole

  seldon:
    docker:
    - image: docker
    working_directory: ~/repo
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - run:
       name: Seldon installation
       command: |
         make gke-seldon-install
    - run:
       name: Seldon build and push
       command: |
         make seldon-build seldon-push
    - run:
        name: Deploy Cartpole Seldon Model
        command: |
          MODEL_TYPE=model make gke-seldon-cartpole
    - run:
        name: Deploy Cartpole Seldon ABTest
        command: |
          MODEL_TYPE=abtest make gke-seldon-cartpole
    - run:
        name: Deploy Cartpole Seldon Router
        command: |
          MODEL_TYPE=router make gke-seldon-cartpole

workflows:
  version: 2
  build:
    jobs:
    - tests