version: 2

references:

  container_config: &container_config
    docker:
    - image: docker
    environment:
      SHELL: "/bin/sh"
    working_directory: ~/repo
  remote_docker_config: &remote_config_docker
    setup_remote_docker:
      reusable: true
      docker_layer_caching: true
  install_make: &install_make
    run:
      name: Install essentials
      command: |
        apk add --no-cache --virtual .build-deps make gcc

jobs:

  tests:
    <<: *container_config
    steps:
    - *remote_docker_config
    - *install_make
    - checkout
    - run:
        name: launch tests
        command: |
          make test

  docker_build_publish:
    <<: *container_config
    steps:
    - *remote_docker_config
    - *install_make
    - checkout
    - run:
        name: docker build
        command: |
          make docker-build
    - run:
        name: docker push
        command: |
          make docker-push

  gke_cluster:
    <<: *container_config
    steps:
    - *remote_docker_config
    - *install_make
    - run:
       name: GCP key file
       command: |
         echo ${GOOGLE_AUTH} > ${HOME}/gcp.json
    - run:
       name: GKE cluster
       command: |
         make gke-bastion gke-create-cluster gke-tiller-helm

  polyaxon:
    <<: *container_config
    steps:
    - *remote_docker_config
    - *install_make
    - run:
       name: Polyaxon installation
       command: |
         make -C polyaxon gke-polyaxon-preinstall gke-polyaxon-install
    - run:
       name: Polyaxon init for cartpole project
       command: |
         make -C polyaxon gke-polyaxon-cartpole-init
    - run:
       name: Cartpole training
       command: |
         make -C polyaxon gke-polyaxon-cartpole

  seldon:
    <<: *container_config
    steps:
    - *remote_docker_config
    - *install_make
    - run:
       name: Seldon installation
       command: |
         make gke-seldon-install
    - run:
       name: Seldon build and push
       command: |
         make seldon-build seldon-push
    - run:
        name: Deploy Cartpole Seldon Model
        command: |
          MODEL_TYPE=model make gke-seldon-cartpole
    - run:
        name: Deploy Cartpole Seldon ABTest
        command: |
          MODEL_TYPE=abtest make gke-seldon-cartpole
    - run:
        name: Deploy Cartpole Seldon Router
        command: |
          MODEL_TYPE=router make gke-seldon-cartpole

workflows:
  version: 2
  build:
    jobs:
    - tests
    - docker_build_publish:
        requires:
        - tests
        filters:
          branches:
            only: master