version: 2
jobs:
  "3.5":
    machine: true
    working_directory: ~/repo
    environment:
      MODEL_FILE: Cartpole-rl-remote-${CIRCLE_BUILD_NUM}.h5
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            pyenv local 3.5.2
            pip install -U pip ipdb tox tox-pyenv
      - run:
          name: test
          command: |
            tox -e py35
      - run:
          name: install and train
          command: |
            make EPOCHS_TRAIN=${EPOCHS_TRAIN} MODEL_FILE=${MODEL_FILE}.h5 install train
      - run:
          name: build and push seldon image
          command: |
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            make MODEL_FILE=${MODEL_FILE} seldon-build seldon-push
  "3.6":
    docker:
    - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install tox
      - run:
          name: test
          command: |
            tox -e py36
      - run:
          name: install
          command: |
            make install
  gce:
    docker:
    - image: google/cloud-sdk
    steps:
    - run: gcloud version

workflows:
  version: 2
  build:
    jobs:
    - "3.6"
    - "3.5":
        requires:
        - "3.6"
    - gce:
        requires:
        - "3.5"