version: '3.3'
services:

  visdom:
    environment:
      - HOSTNAME=visdom
    image: hypnosapos/visdom:latest
    networks:
      default:
        aliases:
          - visdom
    ports:
      - "8097:8097"

  cartpole:
    depends_on:
      - visdom
    links:
      - visdom
    build: ../
    image: hypnosapos/${DOCKER_IMAGE:-cartpole-rl-remote}:${DOCKER_TAG:-latest}
    command: >-
      bash -c "
      until curl --output /dev/null -f --silent http://visdom:8097; do
        sleep 5
      done &&
      cartpole --log-level DEBUG -e ${TRAIN_EPISODES:-200}
      --metrics-engine visdom --metrics-config '{\"server\": \"http://visdom\", \"env\": \"main\"}'
      train --gamma 0.095 0.099 0.001 -f /tmp/models/cartpole-rl-remote"
    volumes:
    - ../.models:/tmp/models
